import { Dispatch, SetStateAction, createContext } from "react";
import { PixelType } from "./Types";
import { simplePlanToGridPlan } from "./Utils";

const emptyLevelPlan = `
......................
......................
......................
......................
......................
......................
......................
......................
......................`;

const defaultValue: {
  plan: PixelType[][];
  updatePlan: Dispatch<SetStateAction<PixelType[][]>>;
} = { plan: simplePlanToGridPlan(emptyLevelPlan), updatePlan: () => {} };

export const PlanContext = createContext(defaultValue);
